packages:
 - 'packages/*'
 - 'packages/cli/*'
 - 'packages/document/*'
 - 'packages/runtime/*'
 - 'packages/generator/*'
 - 'packages/generator/generators/*'
 - 'packages/generator/plugins/*'
 - 'packages/builder/friendly-errors-webpack-plugin/example'
 - 'packages/review/*'
 - 'packages/server/*'
 - 'packages/builder/*'
 - 'packages/module/*'
 - 'packages/solutions/*'
 - 'packages/toolkit/*'
 - 'packages/toolkit/compiler/*'
 - 'scripts/*'
 - 'tests'
 - 'tests/integration/**/*'
 - 'tests/e2e/**/*'
 - 'website/*'
